version: 0.2

# git-credential-helper: no | yes
# env:
#   shell: shell-tag
#   variables:
#     key: "value"
#     key: "value"
#   parameter-store:
#     key: "value"
#     key: "value"
#   exported-variables:
#     - variable
#     - variable
#   secrets-manager:
#     key: secret-id:json-key:version-stage:version-id
        
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - ls -al

  pre_build:
    commands:
      - echo "pre-build"
    
  build:
    commands:
      - echo "build"
    
  post_build:
    commands:
      - echo "post_build"
    
# artifacts:
  
# cache:
#   paths:
#     - path
#     - path