version: 0.2

# git-credential-helper: no | yes
        
phases:
  install:
    # runtime-versions: ## CI를 Build 내에서 한다면 구성하는게 좋음
    #   nodejs: 20
    commands:
      - AWS_ACCOUNT=$(echo $CODEBUILD_BUILD_ARN | awk -F':' '{print $5}')
    
  build:
    commands:
      - cd server
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.ap-northeast-2.amazonaws.com
      - docker build -t ecr_repository .
      - docker tag ecr_repository:latest $AWS_ACCOUNT.dkr.ecr.ap-northeast-2.amazonaws.com/ecr_repository:1
      - docker push $AWS_ACCOUNT.dkr.ecr.ap-northeast-2.amazonaws.com/ecr_repository:1
    
  post_build:
    commands:
      - cd ..
      - REVISON=$(aws ecs describe-task-definition --task-definition arn:aws:ecs:ap-northeast-2:182024812696:task-definition/test-service-container-family | jq -r '.taskDefinition.revision')
      - echo "REVISION >> $REVISON"
      - sed -i 's/${REVISON}/'"$REVISON"'/g' deploy/appspec.yml
      - cat ./deploy/appspec.yml
      - ls -lah ./deploy

artifacts:
  files:
    - "deploy/*"
  
cache:
  paths:
    - "/root/.m2/**/*"